sphinxAssesment/Pages/Client.cshtml.cs
using Azure.Identity;
using BLL.Services;
using BLL.Services.Interfaces;
using DAL.Entities;
using DTOs.ClientDTOS;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sphinxAssesment.Pages
{
    public class ClientModel : PageModel
    {
        private readonly IClientService _clientService;
        public ClientModel (IClientService clientService)
        {
            _clientService = clientService;
        }


        [BindProperty]
        public ClientPageViewModel clientPageViewModel { get; set; }


        public async Task OnGetAsync()
        {
             int page = int.TryParse(Request.Query["pageNo"], out page) ? page : 0;
             clientPageViewModel = new ClientPageViewModel();
             clientPageViewModel.CurrentPage = page;   
             ClientServiceResponse clientServiceResponse = await _clientService.GetALlClientsAsync(page);
             int noOfClients = clientServiceResponse.ClientCount;
             int numberOfPages = (int)Math.Ceiling((double)noOfClients / 10);
             clientPageViewModel.noOfPages = numberOfPages;

             clientPageViewModel.Clients = clientServiceResponse.Clients;
             

        }




        public async Task<IActionResult> OnPostAsync() {

            if (!ModelState.IsValid)
            {
                return RedirectToPage("/Client",new { pageNo = clientPageViewModel.CurrentPage  } );
            }

            ClientServiceResponse clientServiceResponse = await _clientService.CreateClient(clientPageViewModel.createCLientDTO);

            return RedirectToPage("/Client", new { pageNo = clientPageViewModel.CurrentPage });
        }

       
    }

    public class ClientPageViewModel
    {
        public int noOfPages { get; set; }

        public int CurrentPage { get; set; }
        public CreateCLientDTO createCLientDTO { get; set; } = new CreateCLientDTO();

        public List<Client> Clients { get; set; } = new List<Client>() ;


    };

}

sphinxAssesment/Pages/ClientPage.cshtml.cs
using Azure;
using BLL.Services;
using BLL.Services.Interfaces;
using DAL.Entities;
using DTOs.ClientProductDTOs;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sphinxAssesment.Pages
{
    public class ClientPageModel : PageModel
    {
        private readonly IProductService _productService;
        private readonly IClientService _clientService;
        private readonly IClientProductService _clientProductService;
        public ClientPageModel(IProductService productService,IClientService clientService,IClientProductService clientProductService)
        {
            _productService = productService;
            _clientService = clientService;
            _clientProductService = clientProductService;
        }


        [BindProperty]
        public ViewModelClientPage ViewModel { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            ViewModel = new ViewModelClientPage();
            int clientCode = int.TryParse(Request.Query["clientCode"], out clientCode) ? clientCode : 1;
            int page = int.TryParse(Request.Query["pageNo"], out page) ? page : 0;
            ProductServiceResponse productServiceResponse   = await _productService.GetActiveProductsAsync(page);
            ClientServiceResponse clientServiceResponse = await _clientService.GetClientByCodeAsync(clientCode);
            int numberOfPages = (int)Math.Ceiling((double)productServiceResponse.ProductCount / 10);
            ViewModel.numberOfpages = numberOfPages;
            if (!clientServiceResponse.Success)
            {
                return RedirectToPage("/Client");
            }

            ViewModel.ActiveProducts = productServiceResponse.Products;
            ViewModel.CurrentClient = clientServiceResponse.Clients[0];

            return Page();
        }

        public async Task<IActionResult> OnPostAddClientProductAsync() {
            ClientProductServiceResponse serviceResponse =  await _clientProductService.AddClientProductAsync(ViewModel.CreateClientProduct);
            if (!serviceResponse.success)
            {
                return RedirectToPage("/ClientPage", new { clientCode = ViewModel.CreateClientProduct.ClientCode ,ErrorMessege =serviceResponse.Messege});
            }
            return RedirectToPage("/ClientPage", new { clientCode = ViewModel.CreateClientProduct.ClientCode });
        }

    }

    public class ViewModelClientPage
    {
       public int numberOfpages { get; set; } = 1;
       public Client CurrentClient { get; set; } = new Client();

       public List<Product> ActiveProducts { get; set; } = new List<Product>();

       public CreateClientProductDTO CreateClientProduct { get; set; } = new CreateClientProductDTO();

    }
}

sphinxAssesment/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace sphinxAssesment.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

sphinxAssesment/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sphinxAssesment.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

sphinxAssesment/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sphinxAssesment.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

sphinxAssesment/Pages/Products.cshtml.cs
using BLL.Services;
using BLL.Services.Interfaces;
using DAL.Entities;
using DTOs.ProductDTOS;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sphinxAssesment.Pages
{
    public class ProductsModel : PageModel
    {
        private readonly IProductService _productService;
        public ProductsModel(IProductService productService)
        {
            _productService = productService;
        }

        [BindProperty]
        public ProductsViewModel ViewModel { get; set; }

        public async Task OnGetAsync()
        {
            int page = int.TryParse(Request.Query["pageNo"], out page) ? page : 0;
            ViewModel = new ProductsViewModel();
            ProductServiceResponse response =  await _productService.GetProductsAsync(page);
            ViewModel.products = response.Products;
            int numberOfPages = (int)Math.Ceiling((double)response.ProductCount/ 10);
            ViewModel.numberOfpages = numberOfPages;
        }

        public async Task<IActionResult> OnPostAsync() {
            await _productService.CreateProductsAsync(ViewModel.createProductDTO);

            return RedirectToPage();
        }

    }

    public class ProductsViewModel {


        public int numberOfpages { get; set; } = 1;
        public CreateProductDTO createProductDTO { get; set; } = new CreateProductDTO();

        public List<Product> products { get; set; } = new List<Product>();


    };

}

sphinxAssesment/Pages/Client.cshtml
@page
@using DAL.Entities
@using DTOs.ClientDTOS
@model sphinxAssesment.Pages.ClientModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    // clientDTO.Name

   
}


<form method="post">
    <label asp-for="clientPageViewModel.createCLientDTO.Name"></label>
    <input class="form-control w-50" asp-for="clientPageViewModel.createCLientDTO.Name" />
    <span asp-validation-for="clientPageViewModel.createCLientDTO.Name" class="text-danger"></span>

    <label asp-for="clientPageViewModel.createCLientDTO.CLientClass"></label>

    <select class="form-select w-25"  asp-for="clientPageViewModel.createCLientDTO.CLientClass" asp-items="Html.GetEnumSelectList<CLientClass>()">
        <option value="">select a class</option>
    </select>

    <label asp-for="clientPageViewModel.createCLientDTO.State"></label>

    <select class="form-select w-25" asp-for="clientPageViewModel.createCLientDTO.State" asp-items="Html.GetEnumSelectList<State>()">
        <option value="">select a State</option>
    </select>

    <button class="btn btn-primary" type="submit">Submit</button>
</form>

<div>

    @for (var i = 0; i < Model.clientPageViewModel.noOfPages; i++)
    {
        <a asp-page="/Client" asp-route-pageNo="@i">@i</a>

    }

</div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => Model.clientPageViewModel.Clients[0].Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => Model.clientPageViewModel.Clients[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => Model.clientPageViewModel.Clients[0].State)
                </th>
                <th>
                    @Html.DisplayNameFor(model => Model.clientPageViewModel.Clients[0].CLientClass)
                </th>
                <th></th>
            </tr>
        </thead>

    <tbody>
    @foreach (Client client in Model.clientPageViewModel.Clients){
    <tr>
            <td>
                @Html.DisplayFor(modelItem => client.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => client.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem =>  client.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => client.CLientClass)
            </td>
            <td>
               <a asp-page="/ClientPage" asp-route-clientCode="@client.Code">Client page</a>
            </td>

    </tr>
}
    </tbody>
</table>






<script src="/lib/jquery/dist/jquery.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

sphinxAssesment/Pages/ClientPage.cshtml
@page
@using DAL.Entities;
@model sphinxAssesment.Pages.ClientPageModel
@{
}

<h3>Client Page</h3>

<h4>Client Name :@Model.ViewModel.CurrentClient.Name</h4>
<p>Client Class :@Model.ViewModel.CurrentClient.CLientClass</p>
<p>Client Code :@Model.ViewModel.CurrentClient.Code</p>
<p>Client State :@Model.ViewModel.CurrentClient.State</p>

<br />
<a asp-page="/Edit/EditClient" asp-route-ClientCode="@Model.ViewModel.CurrentClient.Code" class="btn btn-primary" role="button">Edit</a>

<h5>
    clientProducts
</h5>

<div class="container">


    
<div>

    @foreach (var ClientP in Model.ViewModel.CurrentClient.ClientProducts)
    {
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">@ClientP.Product.Name</h5>
                <p class="card-text">Lisence: @ClientP.License</p>
                <a asp-page="/Edit/EditClientProduct" asp-route-ClientCode="@ClientP.ClientCode" asp-route-ProductId="@ClientP.ProductId"  class="btn btn-primary" role="button">Edit</a>
            </div>
            
        </div>




    }

</div>


    @for (var i = 0; i < Model.ViewModel.numberOfpages; i++)
    {
        <a asp-page="/ClientPage" asp-route-clientCode="@Model.ViewModel.CurrentClient.Code" asp-route-pageNo="@i">@i</a>
    }
<div class="row">
@foreach(Product product in Model.ViewModel.ActiveProducts){
        <div id="@product.ProductId" class="card" style="width: 18rem;overflow:hidden">
            <div class="card-body">
                <h5 class="card-title">@product.Name</h5>
                <p class="card-text">@product.Description</p>
                <button onclick="AddToclientButton('@product.ProductId.ToString()')" class="btn btn-primary">Add To client</button>

                <div id="form-@product.ProductId" style="display: none;">
                    <form asp-page="/ClientPage" asp-page-handler="AddClientProduct">

                        <input asp-for="ViewModel.CreateClientProduct.ProductId" type="hidden" value="@product.ProductId">
                        <input asp-for="ViewModel.CreateClientProduct.ClientCode" type="hidden" value="@Model.ViewModel.CurrentClient.Code">

                        <label class="form-label" asp-for="ViewModel.CreateClientProduct.License"></label>
                        <input class="form-control" asp-for="ViewModel.CreateClientProduct.License">
                        <span asp-validation-for="ViewModel.CreateClientProduct.License" class="text-danger"></span>

                        <input class="form-date" asp-for="ViewModel.CreateClientProduct.StartData">
                        <span asp-validation-for="ViewModel.CreateClientProduct.StartData" class="text-danger"></span>

                        <input asp-for="ViewModel.CreateClientProduct.EndData">
                        <span asp-validation-for="ViewModel.CreateClientProduct.EndData" class="text-danger"></span>

                        <button class="btn btn-primary" type="submit">Submit</button>

                    </form>
                </div>

            </div>
        </div>
}
</div>

</div>
<script src="/lib/jquery/dist/jquery.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script>
    function AddToclientButton(Id){

        const form = document.getElementById(`form-${Id}`);

        // Toggle the display property between 'none' and 'block'
        if (form.style.display === 'none') {
            form.style.display = 'block'; // Show the form
        } else {
            form.style.display = 'none';  // Hide the form
        }
    }
</script>

sphinxAssesment/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

sphinxAssesment/Pages/Products.cshtml
@page
@using DAL.Entities
@model sphinxAssesment.Pages.ProductsModel

@{
}



<form method="post" >
    

    <div class="form-outline ">
    <label class="form-label" asp-for="ViewModel.createProductDTO.Name" ></label>
    <input class="form-control w-50" asp-for="ViewModel.createProductDTO.Name">
    </div>
    <br />
    <span asp-validation-for="ViewModel.createProductDTO.Name" class="text-danger"></span>

    <br />
    
    <label class="form-label" asp-for="ViewModel.createProductDTO.Description"></label>
    <input class="form-control w-50" asp-for="ViewModel.createProductDTO.Description">
    
    <br />
    <span asp-validation-for="ViewModel.createProductDTO.Description" class="text-danger"></span>
    <br />
    <label class="form-label" asp-for="ViewModel.createProductDTO.IsActive"></label>
    <input class="form-check-input" asp-for="ViewModel.createProductDTO.IsActive">
    <br />
    <span asp-validation-for="ViewModel.createProductDTO.IsActive" class="text-danger"></span>
    <br />

    <button class="btn btn-primary" type="submit">Submit</button>
   
</form>


@for (var i = 0; i < Model.ViewModel.numberOfpages; i++)
{
    <a asp-page="/Products" asp-route-pageNo="@i">@i</a>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.ViewModel.products[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.ViewModel.products[0].Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.ViewModel.products[0].IsActive)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (Product product in Model.ViewModel.products)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => product.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => product.IsActive)
                </td>
                <td>
                    <a asp-page="/Edit/EditProduct" asp-route-ProductId ="@product.ProductId" class="btn btn-primary" role="button">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>



<script src="/lib/jquery/dist/jquery.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>