sphinxAssesment/Pages/Edit/EditClient.cshtml.cs
using BLL.Services;
using BLL.Services.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sphinxAssesment.Pages.Edit
{
    public class EditClientModel : PageModel
    {
        private readonly IClientService _clientService;
        public EditClientModel(IClientService clientService)
        {
            _clientService = clientService; 
        }

        [BindProperty]
        public ViewModelEditClient ViewModel { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            ViewModel = new ViewModelEditClient();

            int clientCode = int.TryParse(Request.Query["clientCode"], out clientCode) ? clientCode : 1;
            ClientServiceResponse serviceResponse =  await _clientService.GetJustClientByCodeAsync(clientCode);
            if (!serviceResponse.Success) {
                return RedirectToPage("/Client");
            }
            ViewModel.CurrentCLient = serviceResponse.Clients[0];

            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync() {

            ClientServiceResponse serviceRespnose = await _clientService.DeleteClientAsync(ViewModel.CurrentCLient.Code);
            if (!serviceRespnose.Success) { 
                return RedirectToPage("/Edit/EditClient",new { clientCode = ViewModel.CurrentCLient.Code });
            }
            return RedirectToPage("/Client" ,new {Messege ="deleted succesfully" });



        }

        public async Task<IActionResult> OnPostEditAsync()
        {

            ClientServiceResponse serviceRespnose = await _clientService.EditClientAsync(ViewModel.CurrentCLient);
            if (!serviceRespnose.Success)
            {
                return RedirectToPage("/Edit/EditClient", new { clientCode = ViewModel.CurrentCLient.Code,Messege =serviceRespnose.Messege });
            }
            return RedirectToPage("/Edit/EditClient", new { clientCode = ViewModel.CurrentCLient.Code });

        }


    }

    public class ViewModelEditClient
    {
        public Client toBeEditedClient { get; set; } = new Client();
        public Client CurrentCLient { get; set; } = new Client();

    }


}

sphinxAssesment/Pages/Edit/EditClientProduct.cshtml.cs
using BLL.Services;
using BLL.Services.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sphinxAssesment.Pages.Edit
{
    public class EditClientProductModel : PageModel
    {
        private readonly IClientProductService _clientProductService;
        public EditClientProductModel(IClientProductService clientProductService)
        {
            _clientProductService = clientProductService;
        }


        [BindProperty]
        public ViewModelClientProduct ViewModel { get; set; }
        public async Task<IActionResult> OnGetAsync() { 
        

            ViewModel = new ViewModelClientProduct();
            int clientCode = int.TryParse(Request.Query["clientCode"], out clientCode) ? clientCode : 1;
            Guid ProductId = Guid.TryParse(Request.Query["ProductId"], out ProductId) ? ProductId : Guid.Empty;

            ClientProductServiceResponse serviceResponse = await _clientProductService.GetClientProductByIdAsync(clientCode, ProductId);

            ViewModel.CurrentCliPro = serviceResponse.ClientProducts[0];

            if (!serviceResponse.success)
            {

                return RedirectToPage("/Client");

            }
            return Page();
        }
                
             
       

        public async Task<IActionResult> OnPostEditAsync()
        {
            ClientProductServiceResponse serviceResponse = await _clientProductService.UpdateClientProductAsync(ViewModel.CurrentCliPro);

            if (!serviceResponse.success)
            {
                return RedirectToPage("/ClientPage", new { clientCode = ViewModel.CurrentCliPro.ClientCode, Messege = serviceResponse.Messege });
            }
            return RedirectToPage("/Edit/EditClientProduct", new { ProductId = ViewModel.CurrentCliPro.ProductId.ToString() , clientCode = ViewModel.CurrentCliPro.ClientCode });

        }
        public async Task<IActionResult> OnPostDeleteAsync()
        {
            ClientProductServiceResponse serviceResponse = await _clientProductService.DeleteClientProductAsync(ViewModel.CurrentCliPro.ClientCode,ViewModel.CurrentCliPro.ProductId);

            if (!serviceResponse.success)
            {
                return RedirectToPage("/Edit/EditClientProduct", new { ProductId = ViewModel.CurrentCliPro.ProductId.ToString(), clientCode = ViewModel.CurrentCliPro.ClientCode });

            }
            return RedirectToPage("/ClientPage", new { clientCode = ViewModel.CurrentCliPro.ClientCode, Messege = serviceResponse.Messege });


        }


        public class ViewModelClientProduct {
            public ClientProduct CurrentCliPro { get; set; } = new ClientProduct();

        };
    }
}

sphinxAssesment/Pages/Edit/EditProduct.cshtml.cs
using BLL.Services;
using BLL.Services.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace sphinxAssesment.Pages.Edit
{
    public class EditProductModel : PageModel
    {
        private readonly IProductService _productService;
        public EditProductModel(IProductService productService)
        {
            _productService = productService;
        }


        [BindProperty]
        public ViewModelEditProduct ViewModel { get; set; }
        public async Task<IActionResult> OnGet()
        {

            ViewModel = new ViewModelEditProduct(); 
            Guid ProductId =  Guid.TryParse(Request.Query["ProductId"], out ProductId) ? ProductId : Guid.Empty;
            ProductServiceResponse serviceResponse =await _productService.GetProductById(ProductId);

            if (!serviceResponse.Success)
            {
                return RedirectToPage("/Products");

            }
            ViewModel.CurrentProduct = serviceResponse.Products[0];

            return Page();

        }

        public async Task<IActionResult> OnPostEditAsync() {
        ProductServiceResponse serviceResponse = await _productService.UpdateProductsAsync(ViewModel.CurrentProduct);
        if (!serviceResponse.Success)
        {
            return RedirectToPage("/Products",new { Messege = serviceResponse.messege});
        }
        return RedirectToPage("/Edit/EditProduct" , new  { ProductId = ViewModel.CurrentProduct.ProductId.ToString() });

        }


        public async Task<IActionResult> OnPostDeleteAsync()
        {
            ProductServiceResponse serviceResponse = await _productService.DeleteProductsAsync(ViewModel.CurrentProduct.ProductId);
            if (!serviceResponse.Success)
            {
                return RedirectToPage("/Products", new { Messege = serviceResponse.messege });
            }
            return RedirectToPage("/Products");

        }


    }

    public class ViewModelEditProduct {

        public Product CurrentProduct { get; set; } = new Product();

    }
}

sphinxAssesment/Pages/Edit/EditClient.cshtml
@page
@using DAL.Entities
@model sphinxAssesment.Pages.Edit.EditClientModel
@{
}

<div class="container">


<a asp-page="/ClientPage" asp-route-ClientCode="@Model.ViewModel.CurrentCLient.Code" class="btn btn-primary" role="button">Go back</a>


<form asp-page="/Edit/EditClient" asp-page-handler="Edit">

    <input asp-for="ViewModel.CurrentCLient.Code" value="@Model.ViewModel.CurrentCLient.Code" type="hidden">

    <label asp-for="ViewModel.CurrentCLient.Name"></label>
    <input class="form-control w-50" asp-for="ViewModel.CurrentCLient.Name" value="@Model.ViewModel.CurrentCLient.Name">
    <span asp-validation-for="ViewModel.CurrentCLient.Name" class="text-danger"></span>


    <label asp-for="ViewModel.CurrentCLient.CLientClass"></label>
     <select class="form-select w-25" asp-for="ViewModel.CurrentCLient.CLientClass" asp-items="Html.GetEnumSelectList<CLientClass>()">
        <option value="@Model.ViewModel.CurrentCLient.CLientClass">select a class</option>
    </select>

    <label asp-for="ViewModel.CurrentCLient.State"></label>
    <select class="form-select w-25" asp-for="ViewModel.CurrentCLient.State" asp-items="Html.GetEnumSelectList<State>()">
        <option value="@Model.ViewModel.CurrentCLient.State">select a State</option>
    </select>

    <button class="btn btn-info" type="submit">submit</button>


</form>

    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Delete Client</button>

    <div class="modal" id="myModal" role="dialog">
        <div class="modal-dialog align-items-center">

            
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Delete Client</h4>
                </div>
                <div class="modal-body">
                    <p>Delete the Client.</p>
                    <form asp-page="/Edit/EditClient" asp-page-handler="Delete">
                        <input asp-for="ViewModel.CurrentCLient.Code" type="hidden" value="@Model.ViewModel.CurrentCLient.Code" />
                    <button type="submit" >Delete Client</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

</div>


<script src="/lib/jquery/dist/jquery.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

sphinxAssesment/Pages/Edit/EditClientProduct.cshtml
@page
@model sphinxAssesment.Pages.Edit.EditClientProductModel
@{
}

<a asp-page="/ClientPage" asp-route-ClientCode="@Model.ViewModel.CurrentCliPro.ClientCode" class="btn btn-primary" role="button">Go back</a>



<form asp-page="/Edit/EditClientProduct" asp-page-handler="Edit">
    <input asp-for="ViewModel.CurrentCliPro.ClientCode" value="@Model.ViewModel.CurrentCliPro.ClientCode" type="hidden"></input>
    <input asp-for="ViewModel.CurrentCliPro.ProductId" value="@Model.ViewModel.CurrentCliPro.ProductId" type="hidden"></input>

    <label asp-for="ViewModel.CurrentCliPro.License" ></label>
    <input asp-for="ViewModel.CurrentCliPro.License" value="@Model.ViewModel.CurrentCliPro.License"></input>
    <span asp-validation-for="ViewModel.CurrentCliPro.EndData" class="text-danger"></span>

    
    <label asp-for="ViewModel.CurrentCliPro.StartData"></label>
    <input asp-for="ViewModel.CurrentCliPro.StartData" value="@Model.ViewModel.CurrentCliPro.StartData"></input>
    <span asp-validation-for="ViewModel.CurrentCliPro.EndData" class="text-danger"></span>

    <label asp-for="ViewModel.CurrentCliPro.EndData"></label>
    <input asp-for="ViewModel.CurrentCliPro.EndData" value="@Model.ViewModel.CurrentCliPro.EndData"></input>
    <span asp-validation-for="ViewModel.CurrentCliPro.EndData" class="text-danger"></span>

    <button type="submit">submit</button>
</form>


<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Delete Client Product</button>

<!-- Modal -->
<div class="modal" id="myModal" role="dialog">
    <div class="modal-dialog align-items-center">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Delete Client Product</h4>
            </div>
            <div class="modal-body">
                <p>Delete the Client Product.</p>
                <form asp-page="/Edit/EditClientProduct" asp-page-handler="Delete">
                    <input asp-for="ViewModel.CurrentCliPro.ProductId" type="hidden" value="@Model.ViewModel.CurrentCliPro.ProductId" />
                    <input asp-for="ViewModel.CurrentCliPro.ClientCode" type="hidden" value="@Model.ViewModel.CurrentCliPro.ClientCode" />
                    <button type="submit">Delete Product</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

sphinxAssesment/Pages/Edit/EditProduct.cshtml
@page
@model sphinxAssesment.Pages.Edit.EditProductModel
@{
}

<div class="container">


<a asp-page="/Products" class="btn btn-primary" role="button">Go back</a>

<form asp-page="/Edit/EditProduct" asp-page-handler="Edit">

    <label asp-for="ViewModel.CurrentProduct.ProductId"></label>
    <input  asp-for="ViewModel.CurrentProduct.ProductId" value="@Model.ViewModel.CurrentProduct.ProductId" type="hidden" />
    


    <label asp-for="ViewModel.CurrentProduct.Name"></label>
        <input class="form-control w-50" asp-for="ViewModel.CurrentProduct.Name" value="@Model.ViewModel.CurrentProduct.Name" />
    <span asp-validation-for="ViewModel.CurrentProduct.Name" class="text-danger"></span>

    <label asp-for="ViewModel.CurrentProduct.Description"></label>
    <input class="form-control w-50" asp-for="ViewModel.CurrentProduct.Description" value="@Model.ViewModel.CurrentProduct.Description" />
    <span asp-validation-for="ViewModel.CurrentProduct.Description" class="text-danger"></span>

    <label asp-for="ViewModel.CurrentProduct.IsActive"></label>
    <input asp-for="ViewModel.CurrentProduct.IsActive" value="@Model.ViewModel.CurrentProduct.IsActive" />
    <span asp-validation-for="ViewModel.CurrentProduct.IsActive" class="text-danger"></span>
    <button class="btn btn-primary" type="submit" >Submit</button>
</form>

<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Delete Product</button>

<!-- Modal -->
<div class="modal" id="myModal" role="dialog">
    <div class="modal-dialog align-items-center">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Delete Product</h4>
            </div>
            <div class="modal-body">
                <p>Delete the Product.</p>
                <form asp-page="/Edit/EditProduct" asp-page-handler="Delete">
                    <input asp-for="ViewModel.CurrentProduct.ProductId" type="hidden" value="@Model.ViewModel.CurrentProduct.ProductId" />
                    <button type="submit">Delete Product</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

</div>